---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jeevanka/public_html/hivexapremium.com
    - /bin/cp -R . $DEPLOYPATH
    - /bin/chmod 755 $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    